-- #939: a team's two season switches, signups open and wishlist editing open,
-- move onto one row per team and tier.
--
-- Today both live on team_settings.config as signupsOpen and wishlistOpen,
-- one per team with no season attached, so a team cannot have next tier's
-- signups open while this tier's wishlist editing is closed, and the site
-- cannot tell which tier a switch was meant for. Decision 13 on #1189
-- (2026-09-20) made the season app-wide and left a team these two switches
-- per season; this is that row. No row means both switches closed, which is
-- what every reader already did with an absent key: the officer's first
-- click on a tier makes its row, and nothing mints one for a new team or a
-- new tier.
--
-- set_team_season() is the only writer, gated the way team_settings' write
-- policy is today (the team's leader and site admins). A switch passed as
-- null keeps its value, so opening signups does not touch wishlist editing.
-- It writes the audit entries the site used to write from the client, with
-- the tier in the detail.
--
-- The backfill makes a row only where a switch is on: signupsOpen lands on
-- the tier activeSignupSeason names, wishlistOpen on the Season View tier
-- if one is set, else the tier seasonName names (production, 2026-09-21:
-- teams 1 and 2 on MID2; team 3 has signups on with no tier to land on, so
-- its Sign Up button closes until an officer sets one). The two config keys
-- stay: a merge pushes this file before it publishes the site (#1083), and
-- the old bundle keeps reading them for up to ten minutes. #934 strips them
-- when it rewrites the same column.

create table public.team_seasons (
  id bigint generated by default as identity primary key,
  team_id integer not null references public.teams(id) on delete cascade,
  season_code text not null references public.seasons(code),
  signups_open boolean not null default false,
  wishlist_open boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (team_id, season_code)
);

comment on table public.team_seasons is
  'A team''s two switches per tier (#939): whether raiders can sign up and whether they can edit their wishlist. No row means both closed. Written only by set_team_season().';
comment on column public.team_seasons.season_code is 'The tier the switches are for; a seasons.code.';
comment on column public.team_seasons.signups_open is 'Raiders can submit a season signup for this tier (submit_season_signup checks it).';
comment on column public.team_seasons.wishlist_open is 'Raiders can tag and edit their wishlist for this tier (the site and the app check it; the insert path follows in #936).';

alter table public.team_seasons enable row level security;

create policy "Claude readers read team_seasons" on public.team_seasons
  for select to claude_readers using (true);
-- Read on every load of a team page, the guild page and the app's cards;
-- public read matches team_settings' own "Public read settings" policy.
create policy "Public read team_seasons" on public.team_seasons
  for select using (true);

create or replace function public.set_team_season(
  p_team_id integer,
  p_season_code text,
  p_signups_open boolean default null,
  p_wishlist_open boolean default null
) returns public.team_seasons
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.team_seasons;
begin
  if auth.uid() is null then
    raise exception 'Not signed in';
  end if;

  if not (p_team_id = any (public.my_leader_team_ids()) or public.is_site_admin()) then
    raise exception 'Not authorized';
  end if;

  if not exists (select 1 from public.seasons where code = p_season_code) then
    raise exception '% is not a season this site knows', p_season_code;
  end if;

  insert into public.team_seasons (team_id, season_code, signups_open, wishlist_open)
  values (p_team_id, p_season_code, coalesce(p_signups_open, false), coalesce(p_wishlist_open, false))
  on conflict (team_id, season_code) do update
    set signups_open = coalesce(p_signups_open, team_seasons.signups_open),
        wishlist_open = coalesce(p_wishlist_open, team_seasons.wishlist_open),
        updated_at = now()
  returning * into v_row;

  if p_signups_open is not null then
    perform public.write_audit_log(
      p_team_id,
      case when p_signups_open then 'Signups Opened' else 'Signups Closed' end,
      'team_seasons',
      v_row.id::integer,
      jsonb_build_object('season', p_season_code)
    );
  end if;
  if p_wishlist_open is not null then
    perform public.write_audit_log(
      p_team_id,
      case when p_wishlist_open then 'Wishlist Editing Opened' else 'Wishlist Editing Closed' end,
      'team_seasons',
      v_row.id::integer,
      jsonb_build_object('season', p_season_code)
    );
  end if;

  return v_row;
end;
$$;

revoke all on function public.set_team_season(integer, text, boolean, boolean) from public, anon;
grant execute on function public.set_team_season(integer, text, boolean, boolean) to authenticated;

comment on function public.set_team_season(integer, text, boolean, boolean) is
  'Sets a team''s signups-open and wishlist-open switches for one tier (#939), making the row on the first call; a switch passed as null keeps its value. Team leaders of that team and site admins.';

-- Backfill: the switches that are on, each on the tier its config named.
insert into public.team_seasons (team_id, season_code, signups_open)
select ts.team_id, s.code, true
from public.team_settings ts
join public.seasons s on s.display_name = ts.config->>'activeSignupSeason'
where coalesce((ts.config->>'signupsOpen')::boolean, false);

insert into public.team_seasons (team_id, season_code, wishlist_open)
select ts.team_id, s.code, true
from public.team_settings ts
join public.seasons s
  on s.code = coalesce(nullif(ts.config->>'seasonView', ''), (select code from public.seasons where display_name = ts.config->>'seasonName'))
where coalesce((ts.config->>'wishlistOpen')::boolean, false)
on conflict (team_id, season_code) do update set wishlist_open = true;

-- The signup gate reads the row for the tier the team is taking signups for.
-- Body otherwise as 20260908200838 left it.
create or replace function public.submit_season_signup(
  p_team_id integer,
  p_name_realm text,
  p_class text,
  p_spec text,
  p_off_specs text default '',
  p_main_swap boolean default false,
  p_player_note text default null,
  p_swap_from_name_realm text default null
) returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_config jsonb;
  v_class_spec_id integer;
  v_season text;
  v_signup_id integer;
  v_auth_user_id uuid := auth.uid();
begin
  if v_auth_user_id is null then
    raise exception 'Not signed in';
  end if;

  select config into v_config from public.team_settings where team_id = p_team_id;
  v_season := v_config->>'activeSignupSeason';
  if v_season is null or not exists (
    select 1
    from public.team_seasons ts
    join public.seasons s on s.code = ts.season_code
    where ts.team_id = p_team_id and s.display_name = v_season and ts.signups_open
  ) then
    raise exception 'signups are not open for this team';
  end if;

  select id into v_class_spec_id from public.classes_specs
   where class = p_class and spec = p_spec;
  if not found then
    raise exception 'unknown class/spec: % / %', p_class, p_spec;
  end if;

  insert into public.season_signups (
    team_id, signup_name_realm, class_spec_id, off_specs, main_swap,
    swap_class_spec_id, player_note, season, status, swap_from_name_realm,
    auth_user_id
  ) values (
    p_team_id, p_name_realm,
    case when p_main_swap then null else v_class_spec_id end,
    nullif(p_off_specs, ''), p_main_swap,
    case when p_main_swap then v_class_spec_id else null end,
    nullif(p_player_note, ''), v_season, 'pending',
    case when p_main_swap then nullif(p_swap_from_name_realm, '') else null end,
    v_auth_user_id
  ) returning id into v_signup_id;

  return v_signup_id;
end $$;
