// One-time BoE history import SQL generator (#749).
//
// Reads the legacy BoE sheets' CSV exports from data/boe/ and writes one
// transactional, idempotent SQL file to data/sql/import-boe.sql. Guild-wide:
// one run covers every team, which is why this sits beside generate.js
// (one team per run) instead of inside it. Matching rules and the sheet
// shapes are documented in tables/boe.js.
//
// --- How to run ---
//   node scripts/import/boe.js
//
// Options:
//   --data <dir>       CSV directory (default data/boe). Every CSV in it is
//                      read: the one whose name contains "Form Responses" is
//                      the Google Form response sheet (found events), every
//                      other CSV is a sold sheet (one per season). Google's
//                      export names work unrenamed.
//   --out <file>       output (default data/sql/import-boe.sql)
//   --tz <zone>        spreadsheet timezone for wall-clock timestamps
//                      (default America/New_York, same as generate.js)
//   --seasons <file>   season ranges JSON [{code, name, start, end?}] used to
//                      fill boe_items.season by found date (default
//                      data/seasons.json); the file opens with a check that
//                      every code it stamps is a seasons row (#938)
//   --floor <gold>     payout floor snapshot for imported sales (default 20000)
//   --pivot <gold>     payout pivot snapshot for imported sales (default 100000)
//
// The exports pair finder names with payout amounts, so they stay in the
// gitignored data/ directory and are never attached to the public tracker.
//
// Apply with psql as the admin service, then verify the counts the summary
// prints:
//
//   psql service=wga-admin -f data/sql/import-boe.sql
//
// Re-applying is additive: NOT EXISTS on (team_id, found_at) skips rows
// already in the table. That also means a sale the sheet records against a
// find that was already imported as open is not applied by a re-run; record
// it in the app instead.

import { readdirSync, readFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { loadCsv } from './lib/csv.js';
import { classifyInputs, parseFound, parseSold, matchSales, boeSql } from './tables/boe.js';
import { seasonGuardStatement } from './lib/sql.js';

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const dataDir = arg('data', join('data', 'boe'));
const outFile = arg('out', join('data', 'sql', 'import-boe.sql'));
const tz = arg('tz', 'America/New_York');
const seasonsFile = arg('seasons', join('data', 'seasons.json'));
const floor = Number(arg('floor', '20000'));
const pivot = Number(arg('pivot', '100000'));

if (!existsSync(dataDir)) {
  console.error(`No such data directory: ${dataDir}`);
  process.exit(1);
}
if (!Number.isFinite(floor) || floor < 0 || !Number.isFinite(pivot) || pivot <= 0) {
  console.error('--floor must be a non-negative number and --pivot a positive one');
  process.exit(1);
}

const { found: foundFile, sold: soldFiles } = classifyInputs(readdirSync(dataDir));
const seasons = existsSync(seasonsFile) ? JSON.parse(readFileSync(seasonsFile, 'utf8')) : null;

const notes = [];
const foundResult = parseFound(loadCsv(join(dataDir, foundFile)), foundFile);
notes.push(...foundResult.warnings);

const sold = [];
let soldSkipped = 0;
for (const file of soldFiles) {
  const result = parseSold(loadCsv(join(dataDir, file)), file);
  sold.push(...result.entries);
  soldSkipped += result.skipped;
  notes.push(...result.warnings);
}

const matched = matchSales(foundResult.entries, sold);
notes.push(...matched.warnings);

const { sql, counts, warnings, seasons: stampedSeasons } = boeSql(matched.rows, { tz, seasons, floor, pivot });
notes.push(...warnings);

const header =
  `-- Generated by scripts/import/boe.js\n` +
  `-- Source: ${dataDir} (${[foundFile, ...soldFiles].join(', ')})  (#749 BoE history import)\n` +
  `-- Idempotent: NOT EXISTS on (team_id, found_at), so re-applying inserts only new rows.\n`;
const body = `${header}\nbegin;\nset client_encoding = 'UTF8';\n\n${seasonGuardStatement(stampedSeasons)}\n\n-- === boe_items ===\n${sql}\ncommit;\n`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, body, 'utf8');

const byTeam = Object.entries(counts.byTeam)
  .map(([id, n]) => `team ${id}: ${n}`)
  .join(', ');
console.log(`Wrote ${outFile}`);
console.log(`  found sheet ${foundFile}: ${foundResult.entries.length} rows parsed, ${foundResult.skipped} skipped`);
console.log(`  sold sheets (${soldFiles.length}): ${sold.length} rows parsed, ${soldSkipped} skipped`);
console.log(
  `  matched ${counts.paid - counts.standalone}, standalone ${counts.standalone}, open ${counts.open}, ` +
    `total ${counts.total} (${byTeam})`
);
console.log(
  `  expected after apply: status paid ${counts.paid}, found ${counts.open}; ` +
    `sum(sale_price) ${counts.salePrice}, sum(finder_payout) ${counts.finderPayout}, sum(guild_cut) ${counts.guildCut}`
);
console.log(
  `  player links attempted: ${counts.playerLinks} (resolve at apply time; unmatched names keep finder_name)`
);
console.log('Verify counts after apply against the numbers above.');
console.log(
  '  Re-runs are additive on (team_id, found_at): a sale the sheet records against an already-imported open find is skipped; record it in the app.'
);
for (const n of notes) console.log(`  NOTE: ${n}`);
